# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abCWtyn9MKugxXYdOlLDBusGKTTM4QZc
"""

import pandas as pd
df = pd.DataFrame(
{"a" :[4, 5, 6],
"b" :[7, 8, 9],
"c" :[10, 11, 12]},
index = [1, 2, 3])

des = df.describe()
shape = df.shape

print("DataFrame is:\n", df)
print("Shape of DataFrame is:", shape)
print("Description of DataFrame is:", shape)

df1 = pd.DataFrame(
[[4, 7, 10],
[5, 8, 11],
[6, 9, 12]],
index=[1, 2, 3],
columns=['x', 'y', 'z'])

concat = pd.concat([df,df1])
melt = pd.melt(df1)
null = concat.fillna(1)
plot = null.plot.hist()

print("DataFrame df1 is:\n", df1)
print("Melt functionality is here:", melt)
print("Result of Concatination is:", concat)
print("Result of Imputation is:\n", null)
print("Result of Bar Plot is:\n", plot)